name: Deploy to Firebase Hosting on merge

on:
   push:
      branches:
         - main

jobs:
   build_and_deploy:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4

         - uses: oven-sh/setup-bun@v1

         - name: Create environment.prod.ts
           env:
              PROD_API_KEY: ${{ secrets.PROD_API_KEY }}
              PROD_AUTH_DOMAIN: ${{ secrets.PROD_AUTH_DOMAIN }}
              PROD_PROJECT_ID: ${{ secrets.PROD_PROJECT_ID }}
              PROD_STORAGE_BUCKET: ${{ secrets.PROD_STORAGE_BUCKET }}
              PROD_MESSAGING_SENDER_ID: ${{ secrets.PROD_MESSAGING_SENDER_ID }}
              PROD_APP_ID: ${{ secrets.PROD_APP_ID }}
              PROD_MEASUREMENT_ID: ${{ secrets.PROD_MEASUREMENT_ID }}
              PROD_RECAPTCHA_KEY: ${{ secrets.PROD_RECAPTCHA_KEY }}
           run: |
              printf 'export const environment = {\n  production: true,\n  firebase: {\n    apiKey: "%s",\n    authDomain: "%s",\n    projectId: "%s",\n    storageBucket: "%s",\n    messagingSenderId: "%s",\n    appId: "%s",\n    measurementId: "%s"\n  },\n  recaptchaSiteKey: "%s"\n};\n' \
              "$PROD_API_KEY" "$PROD_AUTH_DOMAIN" "$PROD_PROJECT_ID" "$PROD_STORAGE_BUCKET" "$PROD_MESSAGING_SENDER_ID" "$PROD_APP_ID" "$PROD_MEASUREMENT_ID" "$PROD_RECAPTCHA_KEY" \
              > src/environments/environment.prod.ts

         - run: bun install
         - name: Correr tests unitarios
           run: bun run test

         - run: bun run build -- --configuration production --project=frontend

         - uses: FirebaseExtended/action-hosting-deploy@v0
           with:
              repoToken: ${{ secrets.GITHUB_TOKEN }}
              firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HELLUZ }}
              channelId: live
              projectId: helluz
